#! / bin / sh

# Descargará lua-tg y descargará y creará la rama "prueba" de tg.
# Escrito para Ubuntu / Debian. Si está ejecutando Arch (el único aceptable
# alternativa), descárguelo usted mismo.

echo  ' Solicitar privilegios de root para instalar los paquetes necesarios: '
echo  ' libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make '
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make
git clone http://github.com/topkecleon/lua-tg
git clone http://github.com/vysheng/tg --recursive -b test
cd tg
./configure
hacer
